apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.default
  labels:
    nephio.org/network-name: default
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.10.1.0/24
    labels:
      nephio.org/network-name: default
      nephio.org/site: core
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.10.2.0/24
    labels:
      nephio.org/network-name: default
      nephio.org/site: regional
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.10.3.0/24
    labels:
      nephio.org/network-name: default
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.f1
  labels:
    nephio.org/network-name: f1
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.5.1.0/24
    labels:
      nephio.org/network-name: f1
      nephio.org/site: regional
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.5.2.0/24
    labels:
      nephio.org/network-name: f1
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.e1
  labels:
    nephio.org/network-name: e1
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.4.1.0/24
    labels:
      nephio.org/network-name: e1
      nephio.org/site: regional
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.4.2.0/24
    labels:
      nephio.org/network-name: e1
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.sbi
  labels:
    nephio.org/network-name: sbi
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.1.1.0/24
    labels:
      nephio.org/network-name: sbi
      nephio.org/site: core
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.1.2.0/24
    labels:
      nephio.org/network-name: sbi
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.n3
  labels:
    nephio.org/network-name: n3
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.3.1.0/24
    labels:
      nephio.org/network-name: n3
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.n6
  labels:
    nephio.org/network-name: n6
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.0.1.0/24
    labels:
      nephio.org/network-name: n6
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.n2
  labels:
    nephio.org/network-name: n2
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.2.1.0/24
    labels:
      nephio.org/network-name: n2
      nephio.org/site: core
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.2.2.0/24
    labels:
      nephio.org/network-name: n2
      nephio.org/site: regional
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}
---
apiVersion: network.app.kuid.dev/v1alpha1
kind: NetworkConfig
metadata:
  name: 5g.n4
  labels:
    nephio.org/network-name: n4
spec:
  topology: 5g
  addressing: dualstack
  prefixes:
  - prefix: 172.6.1.0/24
    labels:
      nephio.org/network-name: n4
      nephio.org/site: core
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  - prefix: 172.6.2.0/24
    labels:
      nephio.org/network-name: n4
      nephio.org/site: edge
      ipam.be.kuid.dev/ipprefix-type: network
      infra.be.kuid.dev/purpose: link-internal
  encapsulation:
    vxlan: {}

