kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: regional
networking:
  podSubnet: "10.197.0.0/16"
  serviceSubnet: "10.98.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.33.2
- role: worker
  image: kindest/node:v1.33.2
